// Replace `cover` URLs with your own photos when ready.
// Reference covers from Goodreads / Wikipedia / retailers — swap anytime.
const BOOKS = [
  { id: 1, title: "Mala", category: "Fiction", priority: "Standard", dmKeyword: "MALA", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=MALA&font=playfair-display" },
  { id: 2, title: "Mala 2", category: "Fiction", priority: "Standard", dmKeyword: "MALA 2", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=MALA+2&font=playfair-display" },
  { id: 3, title: "Hinave", category: "Fiction", priority: "Standard", dmKeyword: "HINAVE", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=HINAVE&font=playfair-display" },
  { id: 4, title: "Sulphite", category: "Fiction", priority: "Curation", dmKeyword: "SULPHITE", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=SULPHITE&font=playfair-display" },
  { id: 5, title: "Maseel", category: "Fiction", priority: "Curation", dmKeyword: "MASEEL", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=MASEEL&font=playfair-display" },
  { id: 6, title: "Bakht", category: "Fiction", priority: "Standard", dmKeyword: "BAKHT", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=BAKHT&font=playfair-display" },
  { id: 7, title: "Bogi No 12", category: "Fiction", priority: "Curation", dmKeyword: "BOGI NO 12", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=BOGI+NO+12&font=playfair-display" },
  { id: 8, title: "Bab-e-Deher", category: "Fiction", priority: "Standard", dmKeyword: "BAB E DEHER", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=BAB-E-DEHER&font=playfair-display" },
  { id: 9, title: "Azazeel", category: "Fiction", priority: "Standard", dmKeyword: "AZAZEEL", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327941580i/12601871.jpg" },
  { id: 10, title: "Usri Yusra", category: "Fiction", priority: "Standard", dmKeyword: "USRI YUSRA", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=USRI+YUSRA&font=playfair-display" },
  { id: 11, title: "Carpediem", category: "Fiction", priority: "Standard", dmKeyword: "CARPEDIEM", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=CARPEDIEM&font=playfair-display" },
  { id: 12, title: "Main Anmol", category: "Fiction", priority: "Standard", dmKeyword: "MAIN ANMOL", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=MAIN+ANMOL&font=playfair-display" },
  { id: 13, title: "Peer-e-Kamil", category: "Spiritual Fiction", priority: "Anchor", dmKeyword: "PEER E KAMIL", cover: "https://upload.wikimedia.org/wikipedia/en/4/47/Pir-e-Kamil.jpg" },
  { id: 14, title: "Aabehayat", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "AABEHAYAT", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1450123456i/28410951.jpg" },
  { id: 15, title: "Kahf (Rabia Khan)", category: "Fiction", priority: "Standard", dmKeyword: "KAHF RABIA KHAN", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=KAHF&font=playfair-display" },
  { id: 16, title: "Kahf (Abdullah Waseem)", category: "Fiction", priority: "Standard", dmKeyword: "KAHF ABDULLAH WASEEM", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=KAHF&font=playfair-display" },
  { id: 17, title: "Jo Bachy Hain Sang Samet Lo", category: "Fiction", priority: "Standard", dmKeyword: "JO BACHY HAIN", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=JO+BACHY+HAIN&font=playfair-display" },
  { id: 18, title: "Ishq-e-Atish", category: "Romance", priority: "Standard", dmKeyword: "ISHQ E ATISH", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=ISHQ-E-ATISH&font=playfair-display" },
  { id: 19, title: "Ehad-e-Alast", category: "Fiction", priority: "Standard", dmKeyword: "EHAD E ALAST", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=EHAD-E-ALAST&font=playfair-display" },
  { id: 20, title: "Yeh Dil Mera", category: "Romance", priority: "Standard", dmKeyword: "YEH DIL MERA", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=YEH+DIL+MERA&font=playfair-display" },
  { id: 21, title: "Seerat-un-Nabi (SAW)", category: "Islamic", priority: "Standard", dmKeyword: "SEERAT UN NABI", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=SEERAT+UN+NABI&font=playfair-display" },
  { id: 22, title: "Khud Se Khud Tak", category: "Self-help Spiritual", priority: "Standard", dmKeyword: "KHUD SE KHUD TAK", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=KHUD+SE+KHUD+TAK&font=playfair-display" },
  { id: 23, title: "Rab Se Jurny Ka Safar", category: "Spiritual", priority: "Standard", dmKeyword: "RAB SE JURNY KA SAFAR", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=RAB+SE+JURNY&font=playfair-display" },
  { id: 24, title: "La Hasil", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "LA HASIL", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348993776i/13588349.jpg" },
  { id: 25, title: "Hasil", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "HASIL", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348993845i/13588350.jpg" },
  { id: 26, title: "Aks", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "AKS", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348993902i/13588351.jpg" },
  { id: 27, title: "Amar Bail", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "AMAR BAIL", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327940460i/10852404.jpg" },
  { id: 28, title: "Man-o-Salwa", category: "Umaira Ahmed", priority: "Standard", dmKeyword: "MAN O SALWA", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327940520i/10852405.jpg" },
  { id: 29, title: "Mushaf (New Edition)", category: "Nemrah Ahmed", priority: "Anchor", dmKeyword: "MUSHAF", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1354034567i/16158529.jpg" },
  { id: 30, title: "JKP (New Edition)", category: "Nemrah Ahmed", priority: "Anchor", dmKeyword: "JKP", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1369101234i/17834567.jpg" },
  { id: 31, title: "Paras", category: "Fiction", priority: "Standard", dmKeyword: "PARAS", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1483526500i/22673666.jpg" },
  { id: 32, title: "Karakoram Ka Taj Mehal", category: "Travel Fiction", priority: "Curation", dmKeyword: "KARAKORAM", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=KARAKORAM&font=playfair-display" },
  { id: 33, title: "Halim", category: "Nemrah Ahmed", priority: "Anchor", dmKeyword: "HALIM", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1505389992i/36238288.jpg" },
  { id: 34, title: "Namal", category: "Nemrah Ahmed", priority: "Anchor", dmKeyword: "NAMAL", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1483526434i/22673665.jpg" },
  { id: 35, title: "Shehr-e-Zaat", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "SHEHR E ZAAT", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327940600i/10852406.jpg" },
  { id: 36, title: "Woh Jo Qarz Rakhty Thy", category: "Fiction", priority: "Standard", dmKeyword: "WOH JO QARZ", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=WOH+JO+QARZ&font=playfair-display" },
  { id: 37, title: "Hurf Se Lafz Tak", category: "Poetry Literary", priority: "Standard", dmKeyword: "HURF SE LAFZ TAK", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=HURF+SE+LAFZ&font=playfair-display" },
  { id: 38, title: "Zindagi Gulzar Hai", category: "Umaira Ahmed", priority: "Anchor", dmKeyword: "ZINDAGI GULZAR HAI", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327940680i/10852407.jpg" },
  { id: 39, title: "Diyare Dil", category: "Romance", priority: "Standard", dmKeyword: "DIYARE DIL", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=DIYARE+DIL&font=playfair-display" },
  { id: 40, title: "Dil Se Nikly Hain Jo Lafz", category: "Poetry", priority: "Standard", dmKeyword: "DIL SE NIKLY HAIN", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=DIL+SE+NIKLY&font=playfair-display" },
  { id: 41, title: "Raja Gidh", category: "Classic Urdu", priority: "Curation", dmKeyword: "RAJA GIDH", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327941000i/10852410.jpg" },
  { id: 42, title: "Malal (Ahmed Rao)", category: "Fiction", priority: "Curation", dmKeyword: "MALAL", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=MALAL&font=playfair-display" },
  { id: 43, title: "Kayi Chand Thy Sar-e-Aasman", category: "Classic Urdu", priority: "Curation", dmKeyword: "KAYI CHAND", cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1327941100i/10852411.jpg" },
  { id: 44, title: "Hijab", category: "Fiction", priority: "Curation", dmKeyword: "HIJAB", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=HIJAB&font=playfair-display" },
  { id: 45, title: "Jo Rukay To Koh-e-Giran Thy Hum", category: "Poetry", priority: "Standard", dmKeyword: "JO RUKAY", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=JO+RUKAY&font=playfair-display" },
  { id: 46, title: "Iblees", category: "Fiction", priority: "Curation", dmKeyword: "IBLEES", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=IBLEES&font=playfair-display" },
  { id: 47, title: "Bismil", category: "Fiction", priority: "Curation", dmKeyword: "BISMIL", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=BISMIL&font=playfair-display" },
  { id: 48, title: "Jabal", category: "Fiction", priority: "Standard", dmKeyword: "JABAL", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=JABAL&font=playfair-display" },
  { id: 49, title: "Chiste Hayat Dawam", category: "Fiction", priority: "Standard", dmKeyword: "CHISTE HAYAT", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=CHISTE+HAYAT&font=playfair-display" },
  { id: 50, title: "Talam Nagri", category: "Fiction", priority: "Standard", dmKeyword: "TALAM NAGRI", cover: "https://placehold.co/400x600/6B4F3A/FAF6F0?text=TALAM+NAGRI&font=playfair-display" },
  { id: 51, title: "Crystal Eyes", category: "Fiction", priority: "Curation", dmKeyword: "CRYSTAL EYES", cover: "https://placehold.co/400x600/7A3E48/FAF6F0?text=CRYSTAL+EYES&font=playfair-display" },
  { id: 52, title: "Ankaboot", category: "Fiction", priority: "Curation", dmKeyword: "ANKABOOT", cover: "https://placehold.co/400x600/A0826D/FAF6F0?text=ANKABOOT&font=playfair-display" },
];

const MOOD_BUNDLES = [
  { name: "Spiritual Journey", emoji: "🕌", books: ["Peer-e-Kamil", "Seerat-un-Nabi (SAW)", "Khud Se Khud Tak", "Rab Se Jurny Ka Safar"] },
  { name: "Intense Love & Pain", emoji: "🔥", books: ["Ishq-e-Atish", "Aabehayat", "Diyare Dil", "Yeh Dil Mera"] },
  { name: "Modern Long Reads", emoji: "📖", books: ["Namal", "JKP (New Edition)", "Mushaf (New Edition)", "Halim", "Paras"] },
  { name: "Umaira Ahmed Shelf", emoji: "✨", books: ["Peer-e-Kamil", "Aabehayat", "Zindagi Gulzar Hai", "Shehr-e-Zaat", "Amar Bail"] },
  { name: "Classic Adab", emoji: "📚", books: ["Raja Gidh", "Kayi Chand Thy Sar-e-Aasman", "Malal (Ahmed Rao)"] },
];
